name: Run Unit Tests

on:
  push:
    branches: ['**']  # Trigger on push to any branch
  pull_request:
    branches: ['**']  # Also trigger on pull requests to any branch

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]  # Test on multiple Node.js versions
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: npm install
        
      - name: Run linting
        run: npm run lint
        continue-on-error: true
        
      - name: Run unit tests
        run: npm run test:ci
        continue-on-error: true
        
      - name: Upload coverage reports
        if: matrix.node-version == '20.x'  # Only upload coverage once
        uses: codecov/codecov-action@v4
        continue-on-error: true
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          
      - name: Upload coverage to artifact
        if: matrix.node-version == '20.x'
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: coverage-report
          path: coverage/

      - name: Notify Telegram with test result
        if: always()
        run: |
          STATUS="PASSED"
          if [ "${{ job.status }}" != 'success' ]; then STATUS="FAILED"; fi
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="GitHub Actions: Unit tests *$STATUS* for ${{ github.repository }} on branch ${{ github.ref_name }}. See: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
